# cloudresourcemanager, used for creating projects
apiVersion: cnrm.cloud.google.com/v1alpha1
kind: CloudService
metadata:
  name: cloudresourcemanager.googleapis.com
  namespace: "issue-label-bot-dev" # {"type":"string","x-kustomize":{"setter":{"name":"gcloud.core.project","value":"issue-label-bot-dev"}}}
spec:
  service: cloudresourcemanager.googleapis.com
