# This file describes the models to load
orgs:
- name: kubeflow
  automl_model: "projects/976279526634/locations/us-central1/models/TCN2113632983515660288" # {"$ref":"#/definitions/io.k8s.cli.setters.automl-model"}
