# This kustomize package defines CNRM resources to create the GCP resources needed
# to deploy Kubeflow.
namespace: "issue-label-bot-dev" # {"type":"string","x-kustomize":{"setBy":"kpt","setter":{"name":"gcloud.core.project","value":"issue-label-bot-dev"}}}
resources:
- cluster
- ingress
- iam
- pipelines
