apiVersion: v1
data:
  appName: code-intelligence
  hostname: code-intelligence.endpoints.issue-label-bot-dev.cloud.goog
  ingressName: envoy-ingress
  ipName: code-intelligence-ip
  istioNamespace: istio-system
  oauthSecretName: kubeflow-oauth
  project: issue-label-bot-dev
  tlsSecretName: envoy-ingress-tls
kind: ConfigMap
metadata:
  labels:
    kustomize.component: iap-ingress
  name: iap-ingress-config-c2924ch89c
  namespace: istio-system
